### ISSUE TITLE
Not working in latest version

### ISSUE THREAD

**Issue by JoshScruggs** [Mark2Mark/Reporter-Toggler#8]
I updated Glyphs (Version 2.5.2 (1163)) and all my Plugins today and the Reporter Toggler stopped working (not showing in sidebar)
I get this error in the macro panel:
```
Traceback (most recent call last):
  File "/Users/jscrug2/Library/Application Support/Glyphs/Repositories/Reporter Toggler/ReporterToggler.glyphsPalette/Contents/Resources/../MacOS/main.py", line 11, in <module>
    _run('plugin.py')
  File "/Users/jscrug2/Library/Application Support/Glyphs/Repositories/Reporter Toggler/ReporterToggler.glyphsPalette/Contents/Resources/../MacOS/main.py", line 9, in _run
    execfile(path, globals(), globals())
  File "/Users/jscrug2/Library/Application Support/Glyphs/Repositories/Reporter Toggler/ReporterToggler.glyphsPalette/Contents/Resources/plugin.py", line 29, in <module>
    class ReporterToggler (PalettePlugin):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 71, in add_convenience_methods
    type_dict['bundleForClass'] = selector(bundleForClass, isClassMethod=True)
AttributeError: No selector setSortID:
```
Thanks!

**Comment by Mark2Mark** [comment]
Thanks for letting me know.
What are ”all my Plugins"?
@schriftgestalt did you recently changed something in the API, that I need to follow up? Thanks :)

**Comment by JoshScruggs** [comment]
Sorry, I just meant that I updated all the plugins that had updates available. 
So that was things like: DeleteSmallPaths, FixZeroHandles, GuageTool, NotePalettes, RedArrow etc…
I deleted and re-installed Reporter Toggler via the Plugin Manager
Thanks!

**Comment by schriftgestalt** [comment]
I didn’t change the API recently. What version did you have before the update?

**Comment by Mark2Mark** [comment]
@schriftgestalt  I got the same on my Mac in the office now.

```
Traceback (most recent call last):
  File ".../ReporterToggler.glyphsPalette/Contents/Resources/../MacOS/main.py", line 11, in <module>
    _run('plugin.py')
  File ".../ReporterToggler.glyphsPalette/Contents/Resources/../MacOS/main.py", line 9, in _run
    execfile(path, globals(), globals())
  File ".../ReporterToggler.glyphsPalette/Contents/Resources/plugin.py", line 29, in <module>
    class ReporterToggler (PalettePlugin):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 71, in add_convenience_methods
    type_dict['bundleForClass'] = selector(bundleForClass, isClassMethod=True)
AttributeError: No selector setSortID:
```

I had it in 1150 and now in 1165 on Mac 10.11.6 El Capitan

**Comment by JoshScruggs** [comment]
Good to know I'm not the only one. I hope you can get it resolved. I really miss it!

**Comment by Mark2Mark** [comment]
Me too! Good thing is, since I got it, I can try to find the problem. Stress on *try*, though …
**Edit** Nope, that traceback refers to something that I’m not able to fix. Looks like something in the SDK is beyond my abilities :/

**Comment by fkett** [comment]
Just add these lines (stolen from the Glyph Note plug-in with permission from @mekkablue):

```python
	def setSortID_(self, id):
		pass
	
	def sortID(self):
		return 0
```

I added a pull request for your convenience 🛩

**Comment by Mark2Mark** [comment]
Merged. Thank you!
